version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 482285049489.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t radtac-repo .
      - docker tag radtac-repo:latest 482285049489.dkr.ecr.us-east-1.amazonaws.com/radtac-repo:latest
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 482285049489.dkr.ecr.us-east-1.amazonaws.com/radtac-repo:latest
  post_build:
    commands:
      - export KUBECONFIG=config
      - kubectl apply -f deployment.yaml,service.yaml
      - kubectl rollout status deployment/server-demo
      - kubectl get pods
